[package]
name = "datafusion-example"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "44.0.0"
datafusion-substrait = "44.0.0"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
